In [2]:
import numpy as np

In [4]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for row in a.flatten():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [15]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [19]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])